### ISSUE TITLE
In grote aantallen factureren zorgt voor vertragingen, foutmeldingen en e-mails die meermaals worden verzonden

### ISSUE THREAD

**Issue by nielswitte** [assistance-online/status#1]
Instructie vooralsnog om tot de release van de nieuwe versie is uitgerold meer dan 1 factuur per keer te factureren (of even te wachten)

Vermoedelijk aanpassing zal 19/02 uitgerold worden en hopelijk ook direct naar productie doorlopen. Als dit niet lukt zal het in de release van 20/02 meelopen, waarmee het mailproces compleet los verwerkt zal worden van de rest van de applicatie

**Comment by RemcoGB** [comment]
Instructie vooralsnog om tot de release van de nieuwe versie is uitgerold meer dan 1 factuur per keer te factureren (of even te wachten). Vermoedelijk aanpassing zal in de release van 20/02 meelopen, waarmee het mailproces compleet los verwerkt zal worden van de rest van de applicatie
