### ISSUE TITLE
Storing AO 12:10

### ISSUE THREAD

**Issue by Asjenw** [assistance-online/status#119]
AO is momenteel niet of minder goed bereikbaar. We zijn aan het kijken wat er aan de hand is. Zodra we meer weten laten we dit weten.

**Comment by nielswitte** [comment]
RCA (Root Cause Analysis) van Microsoft:
> A code bug in the Socket Duplicator service caused the login workflow to perform the SQL instance process ID lookup using an invalid application instance name resulting in a login failure, when such resolution was done in a Zone Redundant SQL Tenant Ring.
> The Socket Duplicator is a reverse proxy application that services all incoming login requests in a DB node and forwards the request to the appropriate SQL Server process in the node. This process keeps a map of each SQL Server process identified by its Service Fabric instance name and its process ID. In a normal login, when the Socket Duplicator receives a login request it uses the first part of the FQDN received from the customer in the request to perform a instance process ID lookup. This first part of the DNS always corresponds to the Service Fabric application instance name as this has been constructed by the SQL Gateway in the previous login step.
