### ISSUE TITLE
Hotfix release 2019.18

### ISSUE THREAD

**Issue by nielswitte** [assistance-online/status#24]
## 11:00 Release begonnen
Uitrol van de patch is begonnen.

## Wijzigingen
Omdat enkele partijen e-mails niet verwerken als de 'From' header niet gevuld is. Deze zou overgenomen moeten worden van de 'Sender'. Echter ging hier iets mis. Daarnaast mochten e-mailadressen niet met een `_` beginnen. Beide punten worden opgelost met deze release. De release staat gepland om 11:00 uur.

* AO-5012 Mailvalidatie bij facturatie nazien

**Comment by bholthof** [comment]
11:50 Release afgerond
