### ISSUE TITLE
Fout bij verzenden acceptatie bericht in alarmcentrale integraties

### ISSUE THREAD

**Issue by rikbosch** [assistance-online/status#26]
## 16:00 Gereed
Update gereed

## 15:22 Update
Bugfix release wordt uitgerold

## 13:28 Update
De fix is gereed en de bugfix release wordt voorbereid

## Melding
Bij de uitlevering van release 2019.20 is er een probleem ontstaan in het verzenden van acceptatie berichten richting alarmcentrales.

Het heeft impact op de volgende integraties:
* Eurocross
* VHD
* SOS

Het probleem is reeds gevonden en we zijn bezig met het implementeren van een fix.

Volgende update om 13:30 of eerder wanneer er zich ontwikkelingen voor doen.

**Comment by abroos** [comment]
De fix is gereed en de bugfix release wordt voorbereid

**Comment by abroos** [comment]
Bugfix release wordt uitgerold

**Comment by abroos** [comment]
Release is afgerond
